project_name: git-lfs
release:
  github:
    owner: git-lfs
    name: git-lfs
# brew:
#   install: bin.install "git-lfs"
builds:
- goos:
  - linux
  - darwin
  - windows
  - freebsd
  goarch:
  - amd64
  - "386"
  goarm:
  - "6"
  main: .
  ldflags: -s -w -X main.commit={{.Commit}}
  binary: git-lfs
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - LICENSE.md
  - README.md
  - CHANGELOG.md
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
